;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-sexp
	c-electric-colon
	c-electric-delete-forward
	c-electric-lt-gt
	c-electric-semi&comma
	c-indent-line-or-region
	dabbrev-expand
	indent-for-tab-command
	kill-region
	markdown-outdent-or-delete
	org-open-line
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	ido-switch-buffer
	shell-command
	slime-autodoc-space
	))
